Dok på tilgansstyring i studio
Altinn/docs pull request #286
Opened 2021-01-25 10:24 UTC by acn-sbuad

2021-01-25 11:09 UTC, altinnadmin requested changes
Veldig bra, men noe småtteri som bør fikses 👍

2021-01-25 11:09 UTC, altinnadmin commented on content/altinn-studio/access-management/_index.md
> +![Repository acccess](images/prod.deploy.1.PNG "Repository acccess")
Om du likevel velger å beholde bildene så dropp uppercase `PNG` og egen images-mappe. Bildene skal ligge i samme mappe som markdown-fila. Bruk også ordentlige navn på bildene, ikke "1", "2", etc. Se https://altinnpedia.ai-dev.brreg.no/about/tools/altinnpedia/tips/#struktur-og-navngivning

2021-01-25 11:09 UTC, altinnadmin commented on content/altinn-studio/access-management/_index.md
> +  Medlemmer i dette teamet jobber med å utvikle applikasjoner og har tigang til samtlige repositories.
Typo: tigang

2021-01-25 11:09 UTC, altinnadmin commented on content/altinn-studio/access-management/_index.md
> +[Mer informasjon kommer]
Kan vurdere å splitte denne doken i to egne undersider hvis det kommer mye her.

2021-01-25 11:30 UTC, acn-sbuad commented on content/altinn-studio/access-management/_index.md
> +  <summary>Konfigurasjon</summary>
Tanken var vel dersom vi forventer at pilotene selv skal opprette disse teamene at det er en enkel konfigurasjon å vise til. Men dersom planen er at vi oppretter og konfigurerer teamene på deres vegne i første omgang holder det kanskje med en punktliste?

2021-01-25 14:09 UTC, altinnadmin commented on content/altinn-studio/access-management/_index.md
> +  <summary>Konfigurasjon</summary>
Tenker at det er vi som gjør dette når vi oppretter nye orgs, mao. ikke noe som må gjøres veldig ofte. Da vil også sannsynligheten for at dette faktisk blir gjort (og bli gjort riktig) øke ;)

2021-01-29 13:31 UTC, lvbachmann reviewed
@acn-sbuad Et par kommentarer du kan vurdere, men utover det mener jeg dette er godt nok til at vi kan ta det inn 👍🏻

2021-01-29 13:31 UTC, lvbachmann commented on content/altinn-studio/access-management/_index.md
> +de øvrige brukerne knyttet til organisasjonen. Dette gjøres via Gitea på følgende lenke: https://altinn.studio/repos/org/{organisasjonsnavn}/teams/
Presisere at det er organisasjonens kortnavn/akronym som skal brukes i URL?

2021-01-29 13:31 UTC, lvbachmann commented on content/altinn-studio/access-management/_index.md
> +#### Konfigurasjon</summary>
Gammel html-tag som er glemt?

2021-01-29 13:41 UTC, altinnadmin approved these changes
Et par småpirk, ellers veldig bra! :)

2021-01-29 13:41 UTC, altinnadmin commented on content/altinn-studio/access-management/_index.md
> +Det er definert fire standard team som legger føringer for en bruker har tillatelse til å gjøre innad i en organisasjon i Altinn Studio.
mangler en "hva" etter "føringer for" :)

2021-01-29 13:41 UTC, altinnadmin commented on content/altinn-studio/access-management/_index.md
> +Ved behov kan man som eier kan man legge til/fjerne brukere i team, oprette nye team og endre konfigurasjon på eksisterende team.
typo: oprette

2021-02-01 08:16 UTC, merged