oppdatert roadmap for autorisasjon
Altinn/docs pull request #344
Opened 2021-04-13 13:54 UTC by sivaglen

Lagt til item 18

2021-04-14 05:36 UTC, altinnadmin requested changes
@sivaglen Bra! Litt smårusk som må fikses før merge.

2021-04-14 05:36 UTC, altinnadmin commented on content/ny-funksjonalitet/roadmap/autorisasjon/_index.md
> +For å sikre tilgangsstyrer for virksomheter med flere underenheter en bedre oversikt på tvers tilbys en funksjonlatiet for å laste ned oversikt over retiigheter som finnes.
Typos: funksjonlatiet + retiigheter

2021-04-14 05:36 UTC, altinnadmin commented on content/ny-funksjonalitet/roadmap/autorisasjon/_index.md
> +Det vil være mulig å hente ut oversikt for hvoedenhet og tilhørende underenheter.
Typo: hvoedenhet

2021-04-14 05:36 UTC, altinnadmin commented on content/ny-funksjonalitet/roadmap/autorisasjon/_index.md
> +![Last ned fil ](skjermbilde_22793.PNG "Last ned fil med oversikt over rettigheter")
- Fjern mellomrom i [Last ned fil` `]
- Endre filnavn til noe beskrivende, f.eks. `last-ned-fil-med-oversikt-over-rettigheter.png`.
  - Bruk `-`, ikke underscore
  - Ikke bruk uppercase `PNG` (dette er en bug i verktøyet du har brukt for å ta screenshot)

2021-04-14 05:36 UTC, altinnadmin commented on content/ny-funksjonalitet/roadmap/autorisasjon/_index.md
> +![Last ned fil ](skjermbilde_22793.PNG "Last ned fil med oversikt over rettigheter")
Screenshot har har også dårlig kvalitet (blurry), og bør fokusere på  panelet som er interessant, ikke ta med hele siden og "Figma" i toppen, det er bare støy.

2021-04-14 07:28 UTC, fsveinsb commented on content/ny-funksjonalitet/roadmap/autorisasjon/_index.md
> +Det vil være mulig å hente ut oversikt for hvoedenhet og tilhørende underenheter.
Typo retiigheter

2021-04-14 07:31 UTC, fsveinsb approved these changes

2021-05-03 07:47 UTC, altinnadmin approved these changes
🥇

2021-05-03 07:48 UTC, sivaglen commented
korrigert

2021-05-03 07:50 UTC, merged