Update referanse-app.md
Altinn/docs pull request #372
Opened 2021-05-03 09:02 UTC by Herskis

Første lenke manglet "rest", https://altinn.github.io/docs/api/rest/kom-i-gang/

2021-05-03 09:32 UTC, elsand requested changes
Bør ikke ha absolutte lenker - det gjør det mer knotete å teste lokalt.

2021-05-03 10:03 UTC, Herskis commented
Har da endret lenke til ikke å være en absolutt.

2021-05-18 11:09 UTC, altinnadmin approved these changes
LGTM

2021-06-02 11:32 UTC, elsand approved these changes

2021-06-02 11:32 UTC, merged